// samples/currency-con-nextui/src/components/CurrencyTable.jsx
const CurrencyTable = ({ usdAmount, euroAmount }) => {
  return (
    <table
      style={{ marginTop: "20px", width: "100%", borderCollapse: "collapse" }}
    >
      <thead>
        <tr>
          <th>Currency</th>
          <th>Amount</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>USA Dollar</td>
          <td>{usdAmount && `$ ${usdAmount}`}</td>
        </tr>
        <tr>
          <td>Euro</td>
          <td>{euroAmount && `€ ${euroAmount}`}</td>
        </tr>
      </tbody>
    </table>
  );
};
export default CurrencyTable;

// samples/currency-con-angularui/src/app/components/currency-table/currency-table.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-currency-table',
  templateUrl: './currency-table.component.html',
  styleUrls: ['./currency-table.component.css'],
})
export class CurrencyTableComponent {
  @Input() usdAmount: number | null;
  @Input() euroAmount: number | null;
}

<table style="margin-top: 20px; width: 100%; border-collapse: collapse">
  <thead>
    <tr>
      <th>Currency</th>
      <th>Amount</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>USA Dollar</td>
      <td>{{ usdAmount && "$ " + usdAmount }}</td>
    </tr>
    <tr>
      <td>Euro</td>
      <td>{{ euroAmount && "€ " + euroAmount }}</td>
    </tr>
  </tbody>
</table>
