// samples/currency-con-angularui/src/app/components/currency-input/currency-input.component.ts
import { Component, EventEmitter, Input, Output } from '@angular/core';

@Component({
  selector: 'app-currency-input',
  templateUrl: './currency-input.component.html',
  styleUrls: ['./currency-input.component.css'],
})
export class CurrencyInputComponent {
  lkrAmount: number;
  @Output() onClick = new EventEmitter<number>();
  @Input() buttonText: string;

  handleConvert() {
    this.onClick.emit(this.lkrAmount);
  }
}

<div>
  <label for="fromAmount">From (LKR)</label>
  <input
    type="number"
    id="fromAmount"
    [(ngModel)]="lkrAmount"
    style="padding: 5px; width: 100px"
  />
  <button (click)="handleConvert()">{{ buttonText }}</button>
</div>

// samples/currency-con-nextui/src/components/CurrencyInput.jsx
import { useState } from "react";

const CurrencyInput = ({ onClick, buttonText }) => {
  const [lkrAmount, setLkrAmount] = useState("");

  const handleInputChange = (event) => {
    setLkrAmount(event.target.value);
  };

  return (
    <div>
      <label htmlFor="fromAmount">From (LKR)</label>
      <input
        type="number"
        id="fromAmount"
        value={lkrAmount}
        onChange={handleInputChange}
        style={{ padding: "5px", width: "100px" }}
      />
      <button onClick={() => onClick(lkrAmount)}>{buttonText}</button>
    </div>
  );
};

export default CurrencyInput;
